[package]
name = "ghost-shell-bar"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
ghost-shell-app.workspace = true
ghost-shell-config.workspace = true
ghost-shell-niri.workspace = true

ghost-shell-widget-audio.workspace = true
ghost-shell-widget-clock.workspace = true
ghost-shell-widget-focus.workspace = true
ghost-shell-widget-menu.workspace = true
ghost-shell-widget-network.workspace = true
ghost-shell-widget-notifications.workspace = true
ghost-shell-widget-power.workspace = true
ghost-shell-widget-workspaces.workspace = true

gpui.workspace = true
gpui-component.workspace = true

anyhow.workspace = true
