[package]
name = "ghost-shell-finder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
ghost-shell-actions.workspace = true
ghost-shell-app.workspace = true
ghost-shell-ipc.workspace = true
ghost-shell-niri.workspace = true

gpui.workspace = true
gpui-component.workspace = true

anyhow.workspace = true
fff-search.workspace = true
neo_frizbee.workspace = true
regex.workspace = true
