[workspace]
resolver = "3"
members = [
  "crates/ghost-shell-actions",
  "crates/ghost-shell-app",
  "crates/ghost-shell-assets",
  "crates/ghost-shell-bar",
  "crates/ghost-shell-cli",
  "crates/ghost-shell-config",
  "crates/ghost-shell-daemon",
  "crates/ghost-shell-ipc",
  "crates/ghost-shell-launcher",
  "crates/ghost-shell-lockscreen",
  "crates/ghost-shell-niri",
  "crates/ghost-shell-widgets/ghost-shell-widget-audio",
  "crates/ghost-shell-widgets/ghost-shell-widget-clock",
  "crates/ghost-shell-widgets/ghost-shell-widget-focus",
  "crates/ghost-shell-widgets/ghost-shell-widget-menu",
  "crates/ghost-shell-widgets/ghost-shell-widget-network",
  "crates/ghost-shell-widgets/ghost-shell-widget-notifications",
  "crates/ghost-shell-widgets/ghost-shell-widget-power",
  "crates/ghost-shell-widgets/ghost-shell-widget-workspaces",
]
default-members = ["crates/ghost-shell-daemon"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"
repository = "https://github.com/thatwhichisdev/ghost-shell"
publish = false

[workspace.dependencies]
ghost-shell-actions = { path = "crates/ghost-shell-actions" }
ghost-shell-app = { path = "crates/ghost-shell-app" }
ghost-shell-assets = { path = "crates/ghost-shell-assets" }
ghost-shell-bar = { path = "crates/ghost-shell-bar" }
ghost-shell-config = { path = "crates/ghost-shell-config" }
ghost-shell-ipc = { path = "crates/ghost-shell-ipc" }
ghost-shell-launcher = { path = "crates/ghost-shell-launcher" }
ghost-shell-lockscreen = { path = "crates/ghost-shell-lockscreen" }
ghost-shell-niri = { path = "crates/ghost-shell-niri" }

ghost-shell-widget-audio = { path = "crates/ghost-shell-widgets/ghost-shell-widget-audio" }
ghost-shell-widget-clock = { path = "crates/ghost-shell-widgets/ghost-shell-widget-clock" }
ghost-shell-widget-focus = { path = "crates/ghost-shell-widgets/ghost-shell-widget-focus" }
ghost-shell-widget-menu = { path = "crates/ghost-shell-widgets/ghost-shell-widget-menu" }
ghost-shell-widget-network = { path = "crates/ghost-shell-widgets/ghost-shell-widget-network" }
ghost-shell-widget-notifications = {
  path = "crates/ghost-shell-widgets/ghost-shell-widget-notifications"
}
ghost-shell-widget-power = { path = "crates/ghost-shell-widgets/ghost-shell-widget-power" }
ghost-shell-widget-workspaces = {
  path = "crates/ghost-shell-widgets/ghost-shell-widget-workspaces"
}

gpui = {
  git = "https://github.com/thatwhichisdev/zed",
  rev = "aa0c1b6acde47fd181f02a6b83fdc894fa3c8135",
  features = [
    "wayland",
  ]
}

gpui_platform = {
  git = "https://github.com/thatwhichisdev/zed",
  rev = "aa0c1b6acde47fd181f02a6b83fdc894fa3c8135",
  features = [
    "wayland",
  ]
}

gpui_tokio = {
  git = "https://github.com/thatwhichisdev/zed",
  rev = "aa0c1b6acde47fd181f02a6b83fdc894fa3c8135",
}

gpui-component = {
  git = "https://github.com/thatwhichisdev/gpui-component",
  rev = "12bdfc28ec11a4357fbddeebb740baa7d3c7b4ee"
}

tokio = {
  version = "1.53.1",
  features = [
    "rt",
    "sync",
  ],
}

anyhow = "1.0.104"
clap = "4.6.4"
jiff = "0.2.35"
rust-embed = "8.12.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.18"
