[workspace]
resolver = "3"
members = [
  "crates/ghost-shell",
  "crates/ghost-shell-app",
  "crates/ghost-shell-audio",
  "crates/ghost-shell-bar",
  "crates/ghost-shell-config",
  "crates/ghost-shell-launcher",
  "crates/ghost-shell-lockscreen",
  "crates/ghost-shell-network",
  "crates/ghost-shell-niri",
  "crates/ghost-shell-notifications",
  "crates/ghost-shell-power",
  "crates/ghost-shell-system"
]
default-members = ["crates/ghost-shell"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"
repository = "https://github.com/thatwhichisdev/ghost-shell"
publish = false

[workspace.dependencies]
ghost-shell-app = { path = "crates/ghost-shell-app" }
ghost-shell-audio = { path = "crates/ghost-shell-audio" }
ghost-shell-bar = { path = "crates/ghost-shell-bar" }
ghost-shell-config = { path = "crates/ghost-shell-config" }
ghost-shell-launcher = { path = "crates/ghost-shell-launcher" }
ghost-shell-lockscreen = { path = "crates/ghost-shell-lockscreen" }
ghost-shell-network = { path = "crates/ghost-shell-network" }
ghost-shell-niri = { path = "crates/ghost-shell-niri" }
ghost-shell-notifications = { path = "crates/ghost-shell-notifications" }
ghost-shell-power = { path = "crates/ghost-shell-power" }
ghost-shell-system = { path = "crates/ghost-shell-system" }

gpui = {
  git = "https://github.com/thatwhichisdev/zed",
  rev = "aa0c1b6acde47fd181f02a6b83fdc894fa3c8135",
  features = [
    "wayland",
  ]
}
gpui_platform = {
  git = "https://github.com/thatwhichisdev/zed",
  rev = "aa0c1b6acde47fd181f02a6b83fdc894fa3c8135",
  features = [
    "wayland",
  ]
}
gpui_tokio = {
  git = "https://github.com/thatwhichisdev/zed",
  rev = "aa0c1b6acde47fd181f02a6b83fdc894fa3c8135",
}

tokio = {
  version = "1.53.1",
  features = [
    "rt",
    "sync",
  ],
}

serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.151"

anyhow = "1.0.104"
thiserror = "2.0.18"

jiff = "0.2.35"
