[package]
name = "ghost-shell-daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[[bin]]
name = "ghost-shell-daemon"
path = "src/main.rs"

[dependencies]
ghost-shell-app.workspace = true
ghost-shell-assets.workspace = true
ghost-shell-bar.workspace = true
ghost-shell-config.workspace = true
ghost-shell-finder.workspace = true
ghost-shell-ipc.workspace = true
ghost-shell-launcher.workspace = true
ghost-shell-lockscreen.workspace = true
ghost-shell-niri.workspace = true
ghost-shell-theme.workspace = true

gpui.workspace = true
gpui-component.workspace = true
gpui_platform.workspace = true
gpui_tokio.workspace = true

anyhow.workspace = true
