[package]
name = "ghost-shell-wallpaper"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
path = "src/wallpaper.rs"

[dependencies]
ghost-shell-app.workspace = true
ghost-shell-config.workspace = true

gpui.workspace = true
gpui_platform.workspace = true
gpui_tokio.workspace = true

anyhow.workspace = true
image = {
  workspace = true,
  features = ["gif", "rayon"],
}
log.workspace = true
lz4_flex = { workspace = true, features = ["safe-decode", "safe-encode", "std"] }
postcard = { workspace = true, features = ["use-std"] }
rayon.workspace = true
serde = { workspace = true, features = ["derive"] }
smallvec.workspace = true
